const ADD_COUNTER = "ADD_COUNTER";
const INITIAL_COUNTER = 0;
const PLUS_COUNT = "PLUS_COUNT";
const MINUS_COUNT = "MINUS_COUNT";
const REMOVE_COUNTER = "REMOVE_COUNTER";
export {ADD_COUNTER,REMOVE_COUNTER,INITIAL_COUNTER,PLUS_COUNT,MINUS_COUNT};
